version: "3.9"

services:
  ferps-anon-bot:
    build: .
    restart: unless-stopped
    env_file: .env
    
    volumes:
      - ./data:/data

    environment:
      - TZ=${TZ}
      - DB_PATH=/data/anonymous.db
      - PORT=8080
      - BASE_URL=${BASE_URL}
    
    ports:
      - "${PORT:-8080}:8080"

